--- 
abstract: ~
author: Ricardo SIGNES, C<< <rjbs@cpan.org> >>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Config-INI
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  IO::File: 0
  IO::String: 0
version: 0.006
