---
abstract: 'simple .ini-file format'
author:
  - 'Ricardo SIGNES, C<< <rjbs@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Config::INI
name: Config-INI
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  Carp: 0
  Mixin::Linewise::Readers: 0.001
  Mixin::Linewise::Writers: 0.001
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rjbs/config-ini.git
version: 0.014
